default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: flashcard-rails-vue_development

test:
  <<: *default
  database: flashcard-rails-vue_test

production:
  <<: *default
  database: flashcard-rails-vue_production
  username: flashcard-rails-vue
  password: <%= ENV['FLASHCARD-RAILS-VUE_DATABASE_PASSWORD'] %>
