default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: flashcard-rails-vue_development
  url: postgres://postgres@localhost:15432

test:
  <<: *default
  database: flashcard-rails-vue_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
